<a href="https://colab.research.google.com/github/dasomnoh/python-/blob/main/numpy_%EB%85%B8%EB%8B%A4%EC%86%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
conda install numpy

ValueError: ignored

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
a = np.arange(6)
type(b)

NameError: ignored

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
1

1

In [ ]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[np.newaxis, : ]

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2 = a[np.newaxis, :] 
a2.shape

(1, 6)

In [ ]:
a.shape

(6,)

In [ ]:
b = [0, 1, 2, 3, 4]
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6,7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,1]

2

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
a[:,1]

array([ 2,  6, 10])

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.zeros(2) 

array([0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.empty(4)

array([2.83874468e-316, 0.00000000e+000, 2.12199579e-314, 6.23537914e+228])

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, num=5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
arr = np.array([2, 5, 9, 1, 10, 42, 27, 6, 10])


In [ ]:
arr

array([ 2,  5,  9,  1, 10, 42, 27,  6, 10])

In [ ]:
np.sort(arr)

array([ 1,  2,  5,  6,  9, 10, 10, 27, 42])

In [ ]:
arr2 = np.sort(arr)[::-1] 
arr2

array([42, 27, 10, 10,  9,  6,  5,  2,  1])

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [ ]:
y = np.array([[2, 4], [1, 3]])
y

array([[2, 4],
       [1, 3]])

In [ ]:
np.sort(y, axis=0) 

array([[1, 3],
       [2, 4]])

In [ ]:
np.argsort(y, axis=0)

array([[1, 1],
       [0, 0]])

In [ ]:
A = np.array([2, 5, 1, 8, 3])
B = np.array([9, 0, 3, 2, 1])
print(np.argsort(A))
print(np.lexsort((A,B)))

[2 0 4 1 3]
[1 4 3 2 0]


In [ ]:
C = np.array([3, 0, 5, 7, 10, 2])
print(np.partition(C,2))

[ 0  2  3  7 10  5]


In [ ]:
print(np.partition(C,-2))

[ 0  2  3  5  7 10]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 9])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 9])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])


In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array([[[0, 1, 2, 3], 
                           [4, 5, 6, 7]],   

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])  

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.reshape(4,2)

ValueError: ignored

In [ ]:
np.reshape(a, newshape=(2, 3), order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
a3 = a[np.newaxis, :3] 
a3

array([[0, 1, 2]])

In [ ]:
a4 = a[:,np.newaxis] 
a4

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[2]

3

In [ ]:
data[0:2]


array([1, 2])

In [ ]:
data[1:]


array([2, 3])

In [ ]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a [ a < 5 ]

array([1, 2, 3, 4])

In [ ]:
a [ a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a [ a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a [ ( a > 2 ) & ( a < 11 ) ]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
arr1

NameError: ignored

In [ ]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2, :]

array([ 9, 10, 11, 12])

In [ ]:
a[:,2]

array([ 3,  7, 11])

In [ ]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99


In [ ]:
a


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a.copy()

In [ ]:
b2[1,1] = 7
b2

array([[99,  2,  3,  4],
       [ 5,  7,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
data = np.array([1, 2])

In [ ]:
ones = np.ones(2, dtype = int)


In [ ]:
data + ones

array([2, 3])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

176

In [ ]:
b = np.array([[1, 1],[2, 2]])

In [ ]:
b.sum()

6

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data.max()

2

In [ ]:
data.sum()

3

In [ ]:
data.min()

1

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a.min()


0.05093587

In [ ]:
a.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]


2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
print(data.max())
print(data.min())
print(data.sum())


6
1
21


In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data


array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row


array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)


In [ ]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)


[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array([1, 2, 3, 4])

In [ ]:
a1 = x.flatten()
a1[0] = 99 
print(x)
print(a1)

[[1 2]
 [3 4]]
[99  2  3  4]


In [ ]:
a2 = x.ravel()  
a2[0] = 98
print(x)  
print(a2)

[[98  2]
 [ 3  4]]
[98  2  3  4]
